<a href="https://colab.research.google.com/github/nausheen53/SMAI/blob/master/1_Copy1_notebook_final_with_knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
import os
import ssl
import sklearn
import numpy as np
import spacy
import re
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use("ggplot")
from sklearn import svm
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
import textblob
from textblob import TextBlob, Word
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

# unpickle data

In [0]:
# from os import walk

# f = []
# for (dirpath, dirnames, filenames) in walk("/home/nausheen/SMAI2/Datasets/Question-1/cifar-10-batches-py"):
#     f.extend(filenames)

# f.remove('readme.html')
# f

In [4]:
import pickle
file='/content/drive/My Drive/Q1/data_batch_5'
with open(file, 'rb') as fo:
    dict_5 = pickle.load(fo, encoding='bytes')
    
file='/content/drive/My Drive/Q1/data_batch_4'
with open(file, 'rb') as fo:
    dict_4 = pickle.load(fo, encoding='bytes')

file='/content/drive/My Drive/Q1/data_batch_3'
with open(file, 'rb') as fo:
    dict_3 = pickle.load(fo, encoding='bytes')

file='/content/drive/My Drive/Q1/data_batch_2'
with open(file, 'rb') as fo:
    dict_2 = pickle.load(fo, encoding='bytes')
    
file='/content/drive/My Drive/Q1/data_batch_1'
with open(file, 'rb') as fo:
    dict_1 = pickle.load(fo, encoding='bytes')


print(dict_1.keys())

# print(dict_1[b'labels'])



print(dict_1[b'data'][1])


dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
[154 126 105 ... 139 142 144]


# concatinate all labels

In [0]:
train_labels = dict_1[b'labels'] + dict_2[b'labels'] +dict_3[b'labels']+dict_4[b'labels']+dict_5[b'labels']

In [0]:
train_array = np.concatenate([dict_1[b'data'],dict_2[b'data'],dict_3[b'data'],dict_4[b'data'],dict_5[b'data']], axis=0)

In [7]:
print(len(train_labels))
print(train_array.shape)

50000
(50000, 3072)


In [0]:
train_array = pd.DataFrame(train_array)
modified_arr = train_array.assign(label = train_labels)

In [9]:
print(modified_arr)

         0    1    2    3    4    5  ...  3067  3068  3069  3070  3071  label
0       59   43   50   68   98  119  ...    57   104   140    84    72      6
1      154  126  105  102  125  155  ...   133   136   139   142   144      9
2      255  253  253  253  253  253  ...    72    79    83    83    84      9
3       28   37   38   42   44   40  ...    48    38    28    37    46      4
4      170  168  177  183  181  177  ...    79    78    82    78    80      1
...    ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...    ...
49995  145  151  156  155  153  153  ...    59    57    56    53    54      2
49996  255  254  255  254  254  254  ...    76    82    79    81    76      6
49997   35   40   42   39   43   45  ...    93    87    77    66    50      9
49998  189  186  185  184  182  181  ...   169   165   169   171   171      1
49999  229  236  234  231  236  242  ...   171   174   173   162   161      1

[50000 rows x 3073 columns]


In [10]:
train=modified_arr.sample(frac=0.8,random_state=200) #random state is a seed value
test=modified_arr.drop(train.index)

Actual_label_train=train['label']
Actual_label_test = test['label']

train = train.drop(['label'],axis=1)
test = test.drop(['label'],axis=1)
print(type(train))
print(type(test))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [0]:
train = np.array(train)
test = np.array(test)

In [0]:
sclr = StandardScaler()
sclr.fit(train)
train_data = sclr.transform(train)
test_data = sclr.transform(test)
pca = PCA(0.85)
pca.fit(train_data)
train = pca.transform(train_data)
test = pca.transform(test_data)

In [13]:
print('train ',train.shape)

train  (40000, 57)


In [15]:
from sklearn.svm import LinearSVC
clf = LinearSVC(C=0.1)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
# support_vectors = clf.support_vectors_
# print("support_vectors ",support_vectors)
# Accu_score = accuracy_score(Actual_label_test,predicted_label)
# print("Accuracy score",Accu_score)


predicted label  [9 6 8 ... 7 8 8]


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [0]:
Accu_score = accuracy_score(Actual_label_test,predicted_label)
print("Accuracy score",Accu_score)
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)
print("accuracy score ",Accu_score)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)
# support_vec = clf.support_vectors_
# print(support_vec)

Accuracy score 0.3347
accuracy score  0.3347
********************
f1 score  [0.38828968 0.39532872 0.1942029  0.21052632 0.26420079 0.31476998
 0.34909091 0.36336032 0.37517241 0.43447669]
********************
recall score  0.3347
********************
confusion matrix  [[378  62  14 145  11  31  14  69 159  98]
 [ 42 457  13  74   9  28  36  47 125 176]
 [106  96 134 162 106  88 123  84  52  29]
 [ 37 126  39 256  24 191  95  68  91  86]
 [ 60  55  65 132 200 100 149 136  49  42]
 [ 24  69  46 249  24 325  74  62  95  36]
 [  9  91  38 154  72 144 336  45  57  36]
 [ 34  68  36 143  72  89  73 359  58  88]
 [211  83   9  55   3  28   8  31 408 162]
 [ 65 198   6  49   5  37  35  55  83 494]]
********************
precision score  0.3416499088762346
********************
classification report                precision    recall  f1-score   support

           0       0.39      0.39      0.39       981
           1       0.35      0.45      0.40      1007
           2       0.34      0.14  

In [0]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5,max_iter=2000,C=0.4)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
# support_vectors = clf.support_vectors_
# print("support_vectors ",support_vectors)
Accu_score = accuracy_score(Actual_label_test,predicted_label)
print("Accuracy score",Accu_score)
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)
print("accuracy score ",Accu_score)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)
# support_vec = clf.support_vectors_
# print(support_vec)

predicted label  [8 6 8 ... 7 8 1]
Accuracy score 0.3025
accuracy score  0.3025
********************
f1 score  [0.34406439 0.36497545 0.16861219 0.1667761  0.28306265 0.25487399
 0.36346778 0.29080404 0.3912436  0.31437768]
********************
recall score  0.3025
********************
confusion matrix  [[342 132  51  37  48  38  28  91 167  47]
 [ 34 446  23  22  40  57  59  63 119 144]
 [115  56 130  42 189 115 148 102  44  39]
 [ 64 119  78 127 107 181  99  90  68  80]
 [ 54  46  60  38 305 127 172 105  36  45]
 [ 85  87  52 118  99 268 112  79  58  46]
 [ 14  75  39  45 119 140 392  71  33  54]
 [ 58  47  63  42 222  97  86 302  52  51]
 [193 177  34  18  15  39  17  47 420  38]
 [ 48 252  32  21  23  37  62 107 152 293]]
********************
precision score  0.2971065622244629
********************
classification report                precision    recall  f1-score   support

           0       0.34      0.35      0.34       981
           1       0.31      0.44      0.36      1007


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [0]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5,max_iter=2000,C=0.01)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
# support_vectors = clf.support_vectors_
# print("support_vectors ",support_vectors)
Accu_score = accuracy_score(Actual_label_test,predicted_label)
print("Accuracy score",Accu_score)
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)
print("accuracy score ",Accu_score)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)
# support_vec = clf.support_vectors_
# print(support_vec)

predicted label  [9 6 8 ... 7 8 8]
Accuracy score 0.3752
accuracy score  0.3752
********************
f1 score  [0.40861244 0.41489822 0.23092505 0.22045315 0.30274136 0.33850776
 0.39400428 0.39126117 0.48053097 0.45937358]
********************
recall score  0.3752
********************
confusion matrix  [[427  66  21  21  15  25  27  68 229  82]
 [ 63 479  10  22  14  40  56  48 100 175]
 [135  74 171  61 120  87 182  77  45  28]
 [ 64 122  51 180  37 196 152  67  62  82]
 [ 80  48  82  48 254  78 188 134  33  43]
 [ 41  84  66 142  50 338 122  75  55  31]
 [ 27  80  37  72  94  83 460  58  27  44]
 [ 49  67  47  50  93  82 103 394  52  83]
 [154  90  11  11   6  37  16  28 543 102]
 [ 69 192   5  13   7  27  47  45 116 506]]
********************
precision score  0.3691686976508904
********************
classification report                precision    recall  f1-score   support

           0       0.39      0.44      0.41       981
           1       0.37      0.48      0.41      1007


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [0]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5,max_iter=5000,C=0.001)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
# support_vectors = clf.support_vectors_
# print("support_vectors ",support_vectors)
Accu_score = accuracy_score(Actual_label_test,predicted_label)
print("Accuracy score",Accu_score)
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)
print("accuracy score ",Accu_score)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)
# support_vec = clf.support_vectors_
# print(support_vec)

predicted label  [9 6 8 ... 7 8 8]
Accuracy score 0.374
accuracy score  0.374
********************
f1 score  [0.40534096 0.4112069  0.2300885  0.21921182 0.29952267 0.33967936
 0.3943299  0.3888335  0.48126928 0.45688488]
********************
recall score  0.374
********************
confusion matrix  [[425  67  21  21  15  25  27  68 229  83]
 [ 64 477  10  22  14  39  56  48 100 177]
 [136  79 169  61 121  85 177  77  46  29]
 [ 65 121  51 178  36 197 153  66  64  82]
 [ 79  52  79  47 251  78 191 134  34  43]
 [ 43  85  67 139  49 339 119  75  55  33]
 [ 30  82  31  69  96  84 459  57  28  46]
 [ 51  66  47  50  93  81 103 390  53  86]
 [153  90  10  12   6  37  14  27 546 103]
 [ 70 194   4  12   7  27  47  44 116 506]]
********************
precision score  0.36812447883644994
********************
classification report                precision    recall  f1-score   support

           0       0.38      0.43      0.41       981
           1       0.36      0.47      0.41      1007
  

In [0]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-5,max_iter=5000,C=0.009)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
# support_vectors = clf.support_vectors_
# print("support_vectors ",support_vectors)
Accu_score = accuracy_score(Actual_label_test,predicted_label)
print("Accuracy score",Accu_score)
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)
print("accuracy score ",Accu_score)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)
# support_vec = clf.support_vectors_
# print(support_vec)

predicted label  [9 6 8 ... 7 8 8]
Accuracy score 0.3753
accuracy score  0.3753
********************
f1 score  [0.40861244 0.41489822 0.23211876 0.22058824 0.30274136 0.33833834
 0.39417309 0.39126117 0.48053097 0.45937358]
********************
recall score  0.3753
********************
confusion matrix  [[427  66  21  21  15  25  27  68 229  82]
 [ 63 479  10  22  14  40  56  48 100 175]
 [135  74 172  61 120  87 181  77  45  28]
 [ 64 122  51 180  37 196 152  67  62  82]
 [ 80  48  82  48 254  78 188 134  33  43]
 [ 41  84  66 142  50 338 122  75  55  31]
 [ 27  80  37  71  94  84 460  58  27  44]
 [ 49  67  47  50  93  82 103 394  52  83]
 [154  90  11  11   6  37  16  28 543 102]
 [ 69 192   5  13   7  27  47  45 116 506]]
********************
precision score  0.3693351101801298
********************
classification report                precision    recall  f1-score   support

           0       0.39      0.44      0.41       981
           1       0.37      0.48      0.41      1007


In [0]:
from sklearn.svm import LinearSVC
clf = LinearSVC(random_state=0, tol=1e-9,max_iter=5000,C=0.001)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
# support_vectors = clf.support_vectors_
# print("support_vectors ",support_vectors)
Accu_score = accuracy_score(Actual_label_test,predicted_label)
# print("Accuracy score",Accu_score)
# support_vec = clf.support_vectors_
# print(support_vec)
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)


predicted label  [9 6 8 ... 7 8 8]


In [0]:
print("accuracy score ",Accu_score)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)

accuracy score  0.374
********************
f1 score  [0.40534096 0.4112069  0.2300885  0.21921182 0.29952267 0.33967936
 0.3943299  0.3888335  0.48126928 0.45688488]
********************
recall score  0.374
********************
confusion matrix  [[425  67  21  21  15  25  27  68 229  83]
 [ 64 477  10  22  14  39  56  48 100 177]
 [136  79 169  61 121  85 177  77  46  29]
 [ 65 121  51 178  36 197 153  66  64  82]
 [ 79  52  79  47 251  78 191 134  34  43]
 [ 43  85  67 139  49 339 119  75  55  33]
 [ 30  82  31  69  96  84 459  57  28  46]
 [ 51  66  47  50  93  81 103 390  53  86]
 [153  90  10  12   6  37  14  27 546 103]
 [ 70 194   4  12   7  27  47  44 116 506]]
********************
precision score  0.36812447883644994
********************
classification report                precision    recall  f1-score   support

           0       0.38      0.43      0.41       981
           1       0.36      0.47      0.41      1007
           2       0.35      0.17      0.23       980
    

   # Train

In [0]:
from sklearn.svm import SVC
clf = SVC(gamma='auto',kernel='linear',max_iter=3000,C=0.001)
clf.fit(train,Actual_label_train)
# print(clf.predict(test))
predicted_label=clf.predict(test)
print("predicted label ",predicted_label)
support_vectors = clf.support_vectors_
print("support_vectors ",support_vectors)
Accu_score = accuracy_score(Actual_label_test,predicted_label)
print("Accuracy score",Accu_score)
support_vec = clf.support_vectors_
print(support_vec)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=3000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


predicted label  [9 6 9 ... 7 8 0]
support_vectors  [[ -4.99397755  -0.20067403   0.29192886 ...  -0.39754556  -0.11983276
    0.21741904]
 [ 58.60529185   5.28028874 -12.87628793 ...   1.13668114  -0.89024523
   -0.25246467]
 [ 49.61817396  14.19130479 -34.6146457  ...   0.98898549   0.8804073
    7.13557781]
 ...
 [ 21.54094994   0.27823047 -22.05176133 ...  -1.9112813   -3.44838956
    0.24411458]
 [ -7.62452897 -19.34964773  12.37476308 ...   1.53091361  -1.71960393
    0.1618911 ]
 [ -7.25544478 -29.17190846 -11.74229717 ...   0.09827706   2.44153955
   -2.14181615]]
Accuracy score 0.3644
[[ -4.99397755  -0.20067403   0.29192886 ...  -0.39754556  -0.11983276
    0.21741904]
 [ 58.60529185   5.28028874 -12.87628793 ...   1.13668114  -0.89024523
   -0.25246467]
 [ 49.61817396  14.19130479 -34.6146457  ...   0.98898549   0.8804073
    7.13557781]
 ...
 [ 21.54094994   0.27823047 -22.05176133 ...  -1.9112813   -3.44838956
    0.24411458]
 [ -7.62452897 -19.34964773  12.37476308 ...   

In [0]:
f11 = f1_score(Actual_label_test, predicted_label,average=None)
re = recall_score(Actual_label_test, predicted_label,average='weighted')
cm = confusion_matrix(Actual_label_test, predicted_label)
pr_sc = precision_score(Actual_label_test, predicted_label,average='weighted')
clrp = classification_report(Actual_label_test, predicted_label)
print("********************")
print("f1 score ",f11)
print("********************")
print("recall score ",re)
print("********************")
print("confusion matrix ",cm)
print("********************")
print("precision score ",pr_sc)
print("********************")
print("classification report ",clrp)

********************
f1 score  [0.36593407 0.44223732 0.20758483 0.2733209  0.31460674 0.2289823
 0.37430168 0.39185991 0.49190939 0.48013669]
********************
recall score  0.3644
********************
confusion matrix  [[333  42  28  47  25  31  25  84 264 102]
 [ 44 423  23  42  24  39  60  53  75 224]
 [101  35 156  94 199  85 133  98  48  31]
 [ 36  66  56 293  63 159 143  74  47  76]
 [ 54  24  69  86 322  67 137 162  26  41]
 [ 22  47  65 303  94 207 116  80  43  27]
 [ 14  37  31 105 191 101 402  57  14  30]
 [ 46  37  54  92 114  56  93 414  35  79]
 [132  53  24  39  15  29  16  16 532 142]
 [ 57 142  17  30  12  30  41  55  81 562]]
********************
precision score  0.3593064775136617
********************
classification report                precision    recall  f1-score   support

           0       0.40      0.34      0.37       981
           1       0.47      0.42      0.44      1007
           2       0.30      0.16      0.21       980
           3       0.26    

In [0]:

print(Actual_label_test)
print(type(Actual_label_test))
Actual_label_test=Actual_label_test.to_list()
final_euclid=[]
for row in train:
  euclid=[]
  for i in range(0,len(test)):
    li=[]
    dis = np.linalg.norm(row - test[i])
    label = Actual_label_test[i]
    li.append(dis)
    li.append(label)
    euclid.append(li)
  euclid.sort()
  final_euclid.append(euclid)
print(final_euclid)

accu_k=[]
predicted_label=[]
K=3
while(K<8):
  predicted_label=[]
  for row in final_euclid:
    euc=[]
    euc=row
    euc=row[0:K]
    print("hiiii")
    li=[]
    for j in range(0,len(euc)):
      print("hello")
      li.append(euc[j][1])
    try:
        modi=mode(li)
    except:
        modi=li[0]
    predicted_label.append(modi)
  accu_k_pair=[]
  accu_score= sklearn.metrics.accuracy_score(Actual_label_test,predicted_label, normalize=True, sample_weight=None)
  print(K)
  print(accu_score," accuracy score")
  print(f1_score(Actual_label_test, predicted_label, average=None)," f1 score")
  # print(K)
  print(confusion_matrix(Actual_label_test,predicted_label)," confusion matrix")
  # print("f1 score for K for euc ",K)
  # print("f1 score ",f1_score)
  accu_k_pair.append(accu_score)
  accu_k_pair.append(K)
  accu_k.append(accu_k_pair)
  K=K+2

accu_k=accu_k.sort()
accu_k.reverse()
K_euclid=accu_k[0][1]
Accuracy_ = accu_k[0][0]
print("final K value ",K_euclid)
print("final accuracy ",Accuracy)






2        9
3        4
4        1
5        1
17       3
        ..
49986    7
49989    1
49992    0
49993    1
49994    0
Name: label, Length: 10000, dtype: int64
<class 'pandas.core.series.Series'>


In [0]:
Significance of C:
In support vector machines,our focus is mainly on getting large margin and lower missclassification
these two things depends on value of C
Keeping a margin low,leads to less missclassifcation in train dataset, however that may not be case in test set.
for Large Value of parameter C,there is small margin and for small value of parameter c,there will be large margin
choosing a value of C depends on dataset
for example when i incresed value of C ,accuracy decreased and when value of c is decreased accuracy increased

SyntaxError: ignored